# This is a basic workflow to help you get started with Actions

name: first_workflow
on: push

jobs:
  first_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: first echo
        run: "echo 'hello world'"
